# Project
mod_version=26.1.0.1
maven_group=com.unrealdinnerbone
curse_id=1048090
mod_name=WeatherGate
mod_author=UnRealDinnerbone
mod_id=weathergate


# Common
minecraft_version=26.1

# Forge
#forge_version=49.0.13

neo_version=26.1.0.8-beta

# Other
trenzalore_version=26.1.0.1

# Other
ftb_lib_version=26.1.0.3-SNAPSHOT
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
